### ISSUE TITLE
0.9.28 make check fail for PKIX1 sample

### ISSUE THREAD

**Issue by brchiu** [vlm/asn1c#91]
On Lubuntu 64bit environment, executing 'make check' under directory of PKIX1 sample.
I got the following error information.

```
Recoding sample-Certificate-1.der into XER and back (1)...
sample-Certificate-1.der: Decode failed past byte 13: Input processing error
Makefile:390: recipe for target 'check-ber' failed
make: *** [check-ber] Error 2
```

Below is some GDB debug information, which shows the failure occurred when decoding CertificateSerialNumber element.

```
Breakpoint 1, asn_INTEGER2long (iptr=0x7fffffffd940, lptr=0x7fffffffd918)
    at INTEGER.c:773
773     if(!iptr || !iptr->buf || !lptr) {
(gdb) n
779     b = iptr->buf;  /* Start of the INTEGER buffer */
(gdb) n
780     size = iptr->size;
(gdb) n
781     end = b + size; /* Where to stop */
(gdb) n
783     if(size > sizeof(long)) {
(gdb) n
784         uint8_t *end1 = end - 1;
(gdb) n
792         for(; b < end1; b++) {
(gdb) n
793             switch(*b) {
(gdb) n
797             break;
(gdb) n
800         size = end - b;
(gdb) n
801         if(size > sizeof(long)) {
(gdb) p size
$5 = 16
(gdb) p sizeof(long)
$6 = 8
(gdb) bt
#0  asn_INTEGER2long (iptr=0x7fffffffd940, lptr=0x7fffffffd918) at INTEGER.c:801
#1  0x00000000004171e4 in NativeInteger_decode_ber (opt_codec_ctx=0x7fffffffdc30, 
    td=0x65b240 <asn_DEF_CertificateSerialNumber>, nint_ptr=0x7fffffffda80, 
    buf_ptr=0x66324f, size=837, tag_mode=0) at NativeInteger.c:111
#2  0x000000000041fdbc in SEQUENCE_decode_ber (opt_codec_ctx=0x7fffffffdc30, 
    td=0x65b100 <asn_DEF_TBSCertificate>, struct_ptr=0x7fffffffdbc0, ptr=0x66324d, 
    size=1115, tag_mode=0) at constr_SEQUENCE.c:412
#3  0x000000000041fdbc in SEQUENCE_decode_ber (opt_codec_ctx=0x7fffffffdc30, 
    td=0x65ade0 <asn_DEF_Certificate>, struct_ptr=0x7fffffffdc98, ptr=0x663244, size=1124, 
    tag_mode=0) at constr_SEQUENCE.c:412
#4  0x0000000000431bd3 in ber_decode (opt_codec_ctx=0x7fffffffdc30, 
    type_descriptor=0x65ade0 <asn_DEF_Certificate>, struct_ptr=0x7fffffffdc98, ptr=0x663240, 
    size=1128) at ber_decoder.c:54
#5  0x0000000000439b1a in data_decode_from_file (pduType=0x65ade0 <asn_DEF_Certificate>, 
    file=0x663010, name=0x7fffffffe300 "sample-Certificate-1.der", suggested_bufsize=8192, 
    on_first_pdu=1) at converter-sample.c:631
#6  0x00000000004388b2 in main (ac=1, av=0x7fffffffdf40) at converter-sample.c:263

(gdb) frame 1
#1  0x00000000004171e4 in NativeInteger_decode_ber (opt_codec_ctx=0x7fffffffdc30, 
    td=0x65b240 <asn_DEF_CertificateSerialNumber>, nint_ptr=0x7fffffffda80, 
    buf_ptr=0x66324f, size=837, tag_mode=0) at NativeInteger.c:111
111             : asn_INTEGER2long(&tmp, &l)) {
(gdb) p *td
$7 = {name = 0x43e5e0 "CertificateSerialNumber", 
  xml_tag = 0x43e5e0 "CertificateSerialNumber", free_struct = 0x417c77 <NativeInteger_free>, 
  print_struct = 0x417b5c <NativeInteger_print>, 
  check_constraints = 0x406818 <CertificateSerialNumber_constraint>, 
  ber_decoder = 0x416ff7 <NativeInteger_decode_ber>, 
  der_encoder = 0x41727f <NativeInteger_encode_der>, 
  xer_decoder = 0x417399 <NativeInteger_decode_xer>, 
  xer_encoder = 0x417574 <NativeInteger_encode_xer>, uper_decoder = 0x0, uper_encoder = 0x0, 
  outmost_tag = 0x0, tags = 0x43e5dc <asn_DEF_CertificateSerialNumber_tags_1>, 
  tags_count = 1, all_tags = 0x43e5dc <asn_DEF_CertificateSerialNumber_tags_1>, 
  all_tags_count = 1, per_constraints = 0x0, elements = 0x0, elements_count = 0, 
  specifics = 0x0}
```

**Comment by brchiu** [comment]
Already solved in recent release.
